### ISSUE TITLE
NameError: name 'files' is not defined. Did you mean: 'filter'?

### ISSUE THREAD

**Issue by funykatebird** [OpenBMB/VisCPM#10]
Python 3.10.11 (main, May 16 2023, 00:28:57) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from VisCPM import VisCPMChat
>>> from PIL import Image
>>> model_path= '/home/jovyan/mm_large_model/viscpm_chat_zhplus_checkpoint.pt'
>>> viscpm_chat = VisCPMChat(model_path, image_safety_checker=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jovyan/mm_large_model/VisCPM/VisCPM/viscpm_chat.py", line 36, in __init__
    files('mypkg.data').joinpath('data1.txt')
NameError: name 'files' is not defined. Did you mean: 'filter'?
>>> exit()

**Comment by Cppowboy** [comment]
请更新到最新版代码，config_path可以传入对应的cpm bee配置文件路径。
