### ISSUE TITLE
Chinese multimodal instruction dataset

### ISSUE THREAD

**Issue by laserwave** [OpenBMB/VisCPM#12]
Thank you for your impressing work. Which multimodal instruction datasets are you using, may be the translated llava 150k data? Will you release the data for Chinese instruction tuning?

**Comment by Cppowboy** [comment]
https://huggingface.co/datasets/cppowboy/llava_zh

**Comment by Cppowboy** [comment]
https://huggingface.co/datasets/openbmb/llava_zh/tree/main
