### ISSUE TITLE
ValueError: assignment destination is read-only

### ISSUE THREAD

**Issue by SeuXiao** [OpenBMB/VisCPM#14]
当我在测试VisCPM时，使用一张本地的图片(一张猫的照片)，询问问题（是否出现猫），出现ValueError: assignment destination is read-only这样的问题
![image](https://github.com/OpenBMB/VisCPM/assets/55699998/635b02b2-8050-4870-a61d-44484f54507a)
，请问应该如何解决，其他图片是可以的。这是因为安全检查的原因吗？

**Comment by Cppowboy** [comment]
相关问题已经修复，可以更新到最新版代码或关闭safety checker再重新测试。
