### ISSUE TITLE
finetune

### ISSUE THREAD

**Issue by nikeaddidaslining** [OpenBMB/VisCPM#15]
Hello！ i want to ask about how to finetuning with lora？

**Comment by Cuiunbo** [comment]
If you need to quickly and cost-effectively fine-tune VisCPM, you can refer to the finetune code in the CPMbee repository. In it, opendelta is used for LoRA-related operations. Below is a link you might want to check out:
https://github.com/OpenBMB/CPM-Bee/blob/main/src/finetune_cpm_bee.py
