### ISSUE TITLE
apple silicon支持

### ISSUE THREAD

**Issue by SeuXiao** [OpenBMB/VisCPM#16]
请问后续有计划将cuda转变为mps加速吗？现在的代码将cuda转变为mps（包括model.to(device)以及torch.mps.empty_cache()）会出现以下问题，不太清楚是什么导致。
![image](https://github.com/OpenBMB/VisCPM/assets/55699998/74c47023-584d-4e1a-88ba-266a7811d80b)

**Comment by Cppowboy** [comment]
从报错信息上看，似乎是数据类型不一致导致的，您可以试下把所有输入数据和模型参数转为float32能不能解决这一问题。
