### ISSUE TITLE
paint无法生成图片

### ISSUE THREAD

**Issue by JACKzhuz** [OpenBMB/VisCPM#17]
在paint任务中，按照readme上的要求，将模型下载下来（两个paint的模型都试了），然后更改demo_paint的路径，可以跑通，出现load  image model  success ! 但是跟他说话他生成不了东西，一直报错错误，别的地方也没有出错，不知为何会这样

**Comment by Cppowboy** [comment]
你好，能否详细描述一下您的报错错误（截图或者完全报错信息），以方便我们帮您定位问题。

**Comment by JACKzhuz** [comment]
没有报错，没有错误信息，就按照要求将下载的模型地址进行了更改，程序也能正常运行，然后在终端success后进入了那个网址，但是你说话让他生成图片生成不了，显示error错误，刷新几遍，使用不同的模型我都试了，依然是这样，比如 在success后进入了网址，我说，生成太阳的图片，他会反应一会然后给我提示error

**Comment by Cppowboy** [comment]
你好，viscpm提供chat和paint两个模型，chat模型用来针对图像做出回答，paint模型用来针对文字描述生成图像。从您的描述看，您是不是用了chat的demo，但使用的是paint的参数文件？你能否给出命令行里的输出或报错信息，方便我们帮您定位问题。另外，您可以加入我们的微信群，更方便地讨论viscpm的使用问题。

**Comment by lonngxiang** [comment]
有点太大了，希望有量化或更小的版本体验
