### ISSUE TITLE
多模态对话效果图

### ISSUE THREAD

**Issue by hunxuewangzi** [OpenBMB/VisCPM#2]
请问有关多模态对话效果图，是根据结果自己画的，还是本身搭建了了一个可以对话的前端界面？
![vlu_case4](https://github.com/OpenBMB/VisCPM/assets/80691681/6fdfd7f0-b958-40d3-ac59-fa1ea2b66d67)

**Comment by JamesHujy** [comment]
你好，上图是根据模型生成结果画的图，我们后续会公布快速部署前端的代码
