### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by pzc163** [OpenBMB/VisCPM#3]
本地环境如下
cuda:11.7
pytorch:1.13.1
python:3.10
GPU：RTX 4090 24G memory
这个报错是什么原因呢？

**Comment by Cppowboy** [comment]
我推测是显存不足导致handle无法初始化，参考 https://discuss.pytorch.org/t/cuda-error-cublas-status-not-initialized-when-calling-cublascreate-handle/125450
