### ISSUE TITLE
请问VisCPM1.1如何加载下载到本地的checkpoint呢？

### ISSUE THREAD

**Issue by zfy1041264242** [OpenBMB/VisCPM#32]
![image](https://github.com/OpenBMB/VisCPM/assets/112854533/0818e842-fceb-407a-b62c-a1d9760ca81a)
![image](https://github.com/OpenBMB/VisCPM/assets/112854533/5f937c87-dee9-4191-8d7c-68a4713ccc99)
![image](https://github.com/OpenBMB/VisCPM/assets/112854533/119a85fd-b683-47fc-99f0-0174b8ccbbb2)
报错信息如上

**Comment by JamesHujy** [comment]
可以将model_path改为./checkpoint/pytorch_model.v1.bin
