### ISSUE TITLE
API 502 Bad Gateway

### ISSUE THREAD

**Issue by yhy-2000** [OpenBMB/VisCPM#34]
Hello, when I try to process images through the API, I got an response '502 Bad Gateway'. Do you know what is the problem? 
![image](https://github.com/OpenBMB/VisCPM/assets/52754849/921274d6-76a1-4686-b55e-ae828dcd3a9b)

**Comment by JamesHujy** [comment]
Due to the resource limitation, we do not provide the VisCPM's API. Please refer to our latest model MiniCPM-V https://github.com/OpenBMB/MiniCPM-V/
