### ISSUE TITLE
微信群过期了，可以更新一下二维码吗？

### ISSUE THREAD

**Issue by newday1255** [OpenBMB/VisCPM#35]
想加入VisCPM交流群和大家一起交流，但是微信群二维码过期了，可以更新一下二维码吗？

另外，我想问下当前VisCPM的web demo支撑多卡推理吗？

**Comment by JamesHujy** [comment]
目前不支持，可以给hujy369@gmail.com发一个邮件，我加一下您微信邀请您入群
