### ISSUE TITLE
在线的demo一直请求失败，api调用也显示http无法连接，麻烦看下是不支持在线使用了吗？

### ISSUE THREAD

**Issue by yatoubusha** [OpenBMB/VisCPM#40]
在线的demo一直请求失败，api调用也显示http无法连接，麻烦看下是不支持在线使用了吗？

**Comment by 545089467** [comment]
+1，我也是

**Comment by JamesHujy** [comment]
您好，限于资源限制，我们目前更新了在线demo部署，请访问我们的新版模型MiniCPM-V的zaixiandemo http://120.92.209.146/
