### ISSUE TITLE
CUDAContext.h:6:10: fatal error: cusparse.h: No such file or directory

### ISSUE THREAD

**Issue by funykatebird** [OpenBMB/VisCPM#5]
cuda11.6
python 3.10 
In file included from /tmp/pip-install-docs1q76/bmtrain_cd370155ab894fa5969602d5d8168e37/csrc/nccl.cpp:4:0:
      /opt/conda/envs/viscpm/lib/python3.10/site-packages/torch/include/ATen/cuda/CUDAContext.h:6:10: fatal error: cusparse.h: No such file or directory

**Comment by Cppowboy** [comment]
您的cuda安装可能有问题，或者是未指定CUDA_HOME。建议您重新安装cuda，并指定CUDA_HOME环境变量后重新测试。
