### ISSUE TITLE
How to chat with text modal only?

### ISSUE THREAD

**Issue by naturesphere** [OpenBMB/VisCPM#9]
If I just want to chat with the visCPM-Chat model in text modal, I don't want to send pictures. How should I organize my input?

**Comment by yaoyuanTHU** [comment]
Thanks for the interest! Currently VisCPM-Chat only supports image-conditioned conversations, meaning that the text-only conversation performance is not so satisfactory right now. If you want to use text-only conversation, you may want to watch the CPM-Bee language model (https://github.com/OpenBMB/CPM-Bee) for further possible release.
